
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      run: reverseproxy
  template:
    metadata:
      labels:
        run: reverseproxy
    spec:
      containers:
        - image: thanhnt103/udagram-reverseproxy:v5
          name: reverseproxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: reverseproxy