name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & Tag the Docker image
        run: |
          docker build -t udagram-api-feed ./udagram-api-feed
          docker build -t udagram-api-user ./udagram-api-user
          docker build -t udagram-frontend ./udagram-frontend
          docker build -t udagram-reverseproxy ./udagram-reverseproxy
          docker tag udagram-api-feed thanhnt103/udagram-api-feed:v9
          docker tag udagram-api-user thanhnt103/udagram-api-user:v9
          docker tag udagram-frontend thanhnt103/udagram-frontend:v9
          docker tag udagram-reverseproxy thanhnt103/udagram-reverseproxy:v7
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push thanhnt103/udagram-api-feed:v9
          docker push thanhnt103/udagram-api-user:v9
          docker push thanhnt103/udagram-frontend:v9
          docker push thanhnt103/udagram-reverseproxy:v7
