name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build -t udagram-api-feed ./udagram-api-feed
        docker build -t udagram-api-user ./udagram-api-user
        docker build -t udagram-frontend ./udagram-frontend
        docker build -t udagram-reverseproxy ./udagram-reverseproxy
        docker tag udagram-api-feed thanhnt103/udagram-api-feed:v1
        docker tag udagram-api-user thanhnt103/udagram-api-user:v1
        docker tag udagram-frontend thanhnt103/udagram-frontend:v1
        docker tag udagram-reverseproxy thanhnt103/udagram-reverseproxy:v1

  login:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Push the Docker image
      run: |
        docker push thanhnt103/udagram-api-feed:v1
        docker push thanhnt103/udagram-api-user:v1
        docker push thanhnt103/udagram-frontend:v1
        docker push thanhnt103/udagram-reverseproxy:v1
