name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ntthanh-99/cd0354-monolith-to-microservices-project

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker --version # print the version for logging
          docker build -t udagram-api-feed ./udagram-api-feed
          docker build -t udagram-api-user ./udagram-api-user
          docker build -t udagram-frontend ./udagram-frontend
          docker build -t reverseproxy ./reverseproxy
          docker tag udagram-api-feed thanhnt103/udagram-api-feed:v1
          docker tag udagram-api-user thanhnt103/udagram-api-user:v1
          docker tag udagram-frontend thanhnt103/udagram-frontend:v1
          docker tag reverseproxy thanhnt103/reverseproxy:v1
          
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
