name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker --version # print the version for logging
        docker build -t udagram-api-feed ./udagram-api-feed
        docker build -t udagram-api-user ./udagram-api-user
        docker build -t udagram-frontend ./udagram-frontend
        docker build -t reverseproxy ./reverseproxy
        docker tag udagram-api-feed thanhnt103/udagram-api-feed:v1
        docker tag udagram-api-user thanhnt103/udagram-api-user:v1
        docker tag udagram-frontend thanhnt103/udagram-frontend:v1
        docker tag reverseproxy thanhnt103/reverseproxy:v1
        echo "$DOCKER_PASSWORD" | docker login -u "ThanhNT103" -p "ntthanh99"
        docker push thanhnt103/udagram-api-feed:v1
        docker push thanhnt103/udagram-api-user:v1
        docker push thanhnt103/udagram-frontend:v1
        docker push thanhnt103/reverseproxy:v1
